### ISSUE TITLE
Buttons do not work in Calculate Fragment 

### ISSUE THREAD

**Issue by ishir21** [anamansari062/NutritionApp#4]

**Comment by cdhiraj40** [comment]
yes, you can go ahead and work on it!

**Comment by SiddyDevelops** [comment]
If this issue has not been solved yet, I would like to solve it. Thank you.

**Comment by cdhiraj40** [comment]
Sorry @SiddyDevelops But  @ishir21 is already working, we will wait for some time and if he will not be able to then sure go ahead and work.
I would suggest you create a new issue/feature as the app is still under development and a new feature will be great ad on :)
